zvenn/src/Entity/Produits.php
<?php

namespace App\Entity;

use App\Repository\ProduitsRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;


/**
 * @ORM\Entity(repositoryClass=ProduitsRepository::class)
 */
class Produits
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */

    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     * min=4,
     * max=10,
     * minMessage = "nom du produit doit etre au minimum {{ limit }} characters long",
     * maxMessage = "nom du produit doit etre au maximum {{ limit }} characters long")
     */

    private $nom_produit;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     * min=4,
     * max=50,
     * minMessage = "nom du produit doit etre au minimum {{ limit }} characters long",
     * maxMessage = "nom du produit doit etre au maximum {{ limit }} characters long")
     */
    private $descriptionp;


    /**
     * @ORM\Column(type="blob")
     */
    private $image_produit;

    private $rawPhoto;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_image;

    /**
     * @ORM\Column (type="datetime")
     */
    private $createdAt;



    public function getNomimage(): ?string
    {
        return $this->nom_image;
    }

    public function setNomimage(string $nom_image): self
    {
        $this->nom_image = $nom_image;

        return $this;
    }




    public function displayPhoto()
    {
        if(null === $this->rawPhoto) {
            $this->rawPhoto = "data:image/png;base64," . base64_encode(stream_get_contents($this->getimageproduit()));
        }

        return $this->rawPhoto;
    }

    /**
     * @ORM\Column(type="float")
     */
    private $prix_produit;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type_produit;

    /**
     * @ORM\ManyToOne(targetEntity=Type::class, inversedBy="produits")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type;



    public function getId(): ?int
    {
        return $this->id;
    }


    public function getnomproduit(): ?string
    {
        return $this->nom_produit;
    }

    public function setNomProduit(string $nom_produit): self
    {
        $this->nom_produit = $nom_produit;

        return $this;
    }

    public function getdescriptionp(): ?string
    {
        return $this->descriptionp;
    }

    public function setDescriptionp(string $descriptionp): self
    {
        $this->descriptionp = $descriptionp;

        return $this;
    }



    public function getimageproduit(File $image = null)
    {
        return $this->image_produit;
    }



    public function setImageProduit($image_produit): self
    {
        $this->image_produit = $image_produit;

        return $this;
    }

    public function getprixproduit(): ?float
    {
        return $this->prix_produit;
    }

    public function setPrixProduit(float $prix_produit): self
    {
        $this->prix_produit = $prix_produit;

        return $this;
    }

    public function getTypeProduit(): ?string
    {
        return $this->type_produit;
    }

    public function setTypeProduit(string $type_produit): self
    {
        $this->type_produit = $type_produit;

        return $this;
    }


    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }
    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;
        return $this;

    }

    public function getType(): ?Type
    {
        return $this->type;
    }

    public function setType(?Type $type): self
    {
        $this->type = $type;

        return $this;
    }


}

zvenn/src/Form/ProduitsType.php
<?php

namespace App\Form;

use App\Entity\Produits;
use App\Entity\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;


class ProduitsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_produit')
            ->add('descriptionp', TextareaType::class)
            ->add('image_produit', FileType::class, [
                'label' => false,
                'multiple' => false,
                'mapped' => false,
                'required' => true
            ])


            ->add('prix_produit')
            ->add('type', EntityType::class, [
                'class' => Type::class,
                'choice_label' => 'nomtype'
            ])
            ->add('type_produit', ChoiceType::class, [
                'choices'  => [
                    'dessert' => 'dessert',
                    'starters' => 'starters',
                    'fastfood' => 'fastfood',

                ]])

        ;


    }



    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Produits::class,
        ]);
    }
}

zvenn/src/Controller/ProduitsController.php
<?php

namespace App\Controller;
use App\Entity\Produits;

use App\Form\ProduitsType;
use App\Repository\ProduitsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;



class ProduitsController extends AbstractController
{
    /**
     * @Route("/produits", name="produits")
     */
    public function index()
    {
        return $this->render('produits/index.html.twig', [
            'controller_name' => 'ProduitsController',
        ]);
    }
    /**
     * @param ProduitsRepository $repository
     * @return Response
     * @Route ("/affiche", name="affiche")
     */
    function Affiche( ){
        $repo=$this->getDoctrine()->getRepository(Produits::class);

        $produits=$repo->findAll();

        return $this->render('index.html.twig',
            [
                'produits'=>$produits,
            ]);
    }
    /**
     * @param Request $request
     * @return Response
     * @Route ("/Ajout",name="Ajout")
     */
    function AjouterProduit(Request $request): Response{
        $produits=new Produits();
        $form=$this->createForm(ProduitsType::class,$produits);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $file = $form->get('image_produit')->getData();
            $uploads_directory = $this->getParameter('uploads_directory');

            $filename = $produits->getnomproduit() . '.' . $file->guessExtension();
            $file->move(
                $uploads_directory,
                $filename
            );
            // On stocke l'image dans la base de données (son nom)

            $produits->setNomimage($filename);

            $produits->setImageProduit($filename);
            $produits->setCreatedAt(new \DateTime());

            $em=$this->getDoctrine()->getManager();

            $em->persist($produits);
            $em->flush();
            return $this->redirectToRoute('affiche');

        }
        return $this->render('produits/ajout.html.twig',
            [
                'produits' => $produits,
                'form'=>$form->createView()]);

    }
    /**
     * @Route("produits/update/{id}",name="update")
     */
    function Update(ProduitsRepository $repository,$id,Request $request)
    {
        $produits = $repository->find($id);
        $form = $this->createForm(ProduitsType::class, $produits);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $file = $form->get('image_produit')->getData();
            $uploads_directory = $this->getParameter('uploads_directory');

            $filename = $produits->getnomproduit() . '.' . $file->guessExtension();
            $file->move(
                $uploads_directory,
                $filename
            );
            // On stocke l'image dans la base de données (son nom)

            $produits->setNomimage($filename);

            $produits->setImageProduit($filename);


            $em = $this->getDoctrine()->getManager();
            $em->flush();
            return $this->redirectToRoute("affiche");
        }
        return $this->render('produits/update.html.twig',
            [
                'form' => $form->createView()
            ]);
    }
    /**
     * @param $id
     * @param ProduitsRepository $rep
     * @Route ("/Delete/{id}", name="delete")
     */
    function Delete($id,ProduitsRepository $rep){
        $produits=$rep->find($id);
        $em=$this->getDoctrine()->getManager();
        $em->remove($produits);
        $em->flush();
        return $this->redirectToRoute('affiche');

    }

}

zvenn/templates/produits/affiche.html.twig
                        <a class="menu_item modal_dialog" href="#modal-dialog">


                                <figure><img src="{{ asset('/uploads/' ~ p.nomimage ) }}"  alt="thumb" class="lazy"></figure>


                                <h3> {{ p.nomproduit }}</h3>
                                <p> {{ p.descriptionp }}</p>
                                <strong>{{ p.prixproduit }}</strong>
                                <strong>{{ p.type.nomtype }}</strong>
                                <a href="{{ path ('update',{'id':p.id}) }}">Update</a>
                                <a href="{{ path ('delete',{'id':p.id}) }}">Delete</a>


                        </a>

<!-- /row -->

zvenn/templates/produits/ajout.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Zvenn - Quality delivery or takeaway food">
    <meta name="Zvenn" content="Zvenn">
    <title>{% block title %}ajouter produit!{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% block stylesheets %}

        <!-- GOOGLE WEB FONT -->
        <link href="{{ asset("https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700&display=swap") }}" rel="stylesheet">
        <!-- BASE CSS -->
        <link href="{{ asset("css/bootstrap_customized.css/bootstrap_customized.min.css") }}" rel="stylesheet">
        <link href="{{ asset("css/style.css") }}" rel="stylesheet">

        <!-- SPECIFIC CSS -->
        <link href="{{asset("css/detail-page.css") }}" rel="stylesheet">

        <!-- YOUR CUSTOM CSS -->
        <link href="{{asset("css/custom.css")  }}" rel="stylesheet">

    {% endblock %}

    {% block javascripts %}
        <!-- COMMON SCRIPTS -->
        <script src="{{"js/common_scripts.min.js" }}"></script>
        <script src="{{ "js/common_func.js" }}"></script>
        <script src="{{ "assets/validate.js" }}"></script>
    {% endblock %}
</head>
{{ include('header.html.twig') }}



{{ form_start(form) }}

<div class="container margin_60_20" id="submit">

    <div class="row justify-content-center">

        <div class="col-lg-5">
            <div class="text-center add_bottom_15">
                <h4>Ajouter un produit</h4>
                <p> Veiller remplir tout les champs </p>
            </div>
        <div class="form-group">
            {{ form_label(form.nom_produit,"Nom Produit") }}

            {{ form_widget(form.nom_produit,{'attr':{
                'placeholder':'nom produits','class':'nom'
            }}) }}
            {{ form_label(form.nom_produit,"Type") }}

            {{ form_widget(form.type)}}
            {{ form_label(form.descriptionp,"description") }}
            {{ form_widget(form.descriptionp,{'attr':{
                'placeholder':'description','class':'description'
            }}) }}
            {{ form_label(form.image_produit,"image") }}
            {{ form_widget(form.image_produit,{'attr':{
                'placeholder':'image produit','class':'image'
            }}) }}
            {{ form_label(form.prix_produit,"prix") }}
            {{ form_widget(form.prix_produit,{'attr':{
                'placeholder':'prix produit','class':'prix'
            }}) }}
            {{ form_label(form.type_produit,"type") }}
            {{ form_widget(form.type_produit,{'attr':{
                'placeholder':'type produit','class':'type'
            }}) }}
            <div class="form-group text-center">
                <button class="btn_1 gradient">Ajouter</button>
            </div>

            {{ form(form,{'method':'GET'}) }}
        </div>
        </div>
    </div>
</div>
{{ form_end(form) }}
{{ include('footer.html.twig') }}

zvenn/templates/produits/update.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="FooYes - Quality delivery or takeaway food">
    <meta name="author" content="Ansonika">
    <title>{% block title %}Welcome!{% endblock %}</title>
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
    {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="shortcut icon" href="{{ asset('images/favicon.ico') }}" type="image/x-icon">
    <link rel="apple-touch-icon" type="image/x-icon" href="{{ asset('/images/apple-touch-icon-57x57-precomposed.png') }}">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="{{ asset('/images/apple-touch-icon-72x72-precomposed.png') }}">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="114x114" href="{{ asset('/images/apple-touch-icon-114x114-precomposed.png') }}">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="144x144" href="{{ asset('/images/apple-touch-icon-144x144-precomposed.png') }}">


    {% block stylesheets %}

        <!-- GOOGLE WEB FONT -->
        <link href="{{ asset("https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700&display=swap") }}" rel="stylesheet">
        <!-- BASE CSS -->
        <link href="{{ asset("css/bootstrap_customized.css/bootstrap_customized.min.css") }}" rel="stylesheet">
        <link href="{{ "css/style.css" }}" rel="stylesheet">

        <!-- SPECIFIC CSS -->
        <link href="{{asset("css/detail-page.css") }}" rel="stylesheet">

        <!-- YOUR CUSTOM CSS -->
        <link href="{{asset("css/custom.css")  }}" rel="stylesheet">

    {% endblock %}

    {% block javascripts %}
        <!-- COMMON SCRIPTS -->
        <script src="{{"js/common_scripts.min.js" }}"></script>
        <script src="{{ "js/common_func.js" }}"></script>
        <script src="{{ "assets/validate.js" }}"></script>
    {% endblock %}
</head>




<div class="container margin_60_20" id="submit">

    <div class="row justify-content-center">

        <div class="col-lg-5">
            <div class="text-center add_bottom_15">
                <h4>modifier un produit</h4>
                <p>Veiller remplir tout les champs </p>
            </div>
            {{ form_start(form) }}
                {{ form_label(form.nom_produit,"Nom Produit") }}

                {{ form_widget(form.nom_produit,{'attr':{
                    'placeholder':'nom produits','class':'nom'
                }}) }}
                {{ form_label(form.descriptionp,"description") }}
                {{ form_widget(form.descriptionp,{'attr':{
                    'placeholder':'description','class':'description'
                }}) }}
                {{ form_label(form.image_produit,"image") }}
                {{ form_widget(form.image_produit,{'attr':{
                    'placeholder':'image produit','class':'image'
                }}) }}
                {{ form_label(form.prix_produit,"prix") }}
                {{ form_widget(form.prix_produit,{'attr':{
                    'placeholder':'prix produit','class':'prix'
                }}) }}
                {{ form_label(form.type_produit,"type") }}
                {{ form_widget(form.type_produit,{'attr':{
                    'placeholder':'type produit','class':'type'
                }}) }}
                <div class="form-group text-center">
                    <button class="btn_1 gradient">modifier</button>
                </div>

                {{ form(form,{'method':'GET'}) }}
            {{ form_end(form) }}
        </div>
    </div>
</div>





<!-- /container -->